# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tdisp"
edition.workspace = true
rust-version.workspace = true

[dependencies]
inspect.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
parking_lot.workspace = true
bitfield-struct.workspace = true
static_assertions.workspace = true

[lints]
workspace = true
