# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "whp"
edition.workspace = true
rust-version.workspace = true

[features]
unstable_whp = []

[dependencies]
pal.workspace = true
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_System_Power"] }
guid.workspace = true

[target.'cfg(windows)'.dev-dependencies]
criterion = { workspace = true, features = ["rayon", "cargo_bench_support"] }
windows-sys = { workspace = true, features = ["Win32_System_Memory", "Win32_System_Threading"] }

[[bench]]
name = "primitives"
harness = false

[lints]
workspace = true
