# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "openhcl_tdisp"
rust-version.workspace = true
edition.workspace = true

[dependencies]
inspect.workspace = true
tdisp.workspace = true
tdisp_proto.workspace = true

anyhow.workspace = true

[lints]
workspace = true
