# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "tdisp_proto"
edition.workspace = true
rust-version.workspace = true

[dependencies]
inspect.workspace = true

prost.workspace = true

[build-dependencies]
prost-build.workspace = true

[lints]
workspace = true
