# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "chipset_device_worker_defs"
edition.workspace = true
rust-version.workspace = true

[dependencies]
vm_resource.workspace = true
mesh.workspace = true
mesh_worker.workspace = true

[lints]
workspace = true
