# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmgs_format"
edition.workspace = true
rust-version.workspace = true

[features]
mesh = ["dep:mesh"]

[dependencies]
inspect = { workspace = true, optional = true }
mesh = { workspace = true, optional = true }
open_enum.workspace = true

bitfield-struct.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true
[lints]
workspace = true
